### ISSUE TITLE
How did you do to convert pdf to json ?

### ISSUE THREAD

**Issue by abedahmeduhp** [zgq354/anki-vscode-shortcuts#1]

**Comment by zgq354** [comment]
I used [this](https://github.com/52cik/vscode-keyboard-shortcuts/blob/master/platforms/mac_en.json), the author may type manually.

**Comment by abedahmeduhp** [comment]
thank you, is there any editor to add values easily?

**Comment by zgq354** [comment]
Maybe you can copy all the text to an editor(like VSCode), then add a delimiter between key and caption for each line. Then you can write a script to split then by the delimiter and make a object. Finally convert it to json.

![image](https://user-images.githubusercontent.com/9024954/94344748-fe14e580-0053-11eb-9bf1-e932d174c205.png)
